### ISSUE TITLE
Change user logged in

### ISSUE THREAD

**Issue by f3d3rica** [AIKEJI-AU/Xero.OAuth2.Docs#5]
How can I remove token or somehow disconnect user logged in? My code invoked xero login window. But I need to change an account, without making changes in code. It's a deployed code on customer site.

**Comment by alice-aikeji** [comment]
> How can I remove token or somehow disconnect user logged in? My code invoked xero login window. But I need to change an account, without making changes in code. It's a deployed code on customer site.

Hi,

You can call ClearLoginSession() method to clear User Login, delete token.json file, relaunch your application to clear token from the memory or call ClearToken() method to clear the token in memory. This will prompt user to login next time you do an API call instead of using the cached details.

Depending on what the requirements are, you may need to implement function that calls those methods in your application.

If you would like your customer to have the option to choose whichever user they log in and use to talk to Xero, then we recommend implementing a button or something in your app that clears the token and user login within the library. The customer can click on it if they wish to login as a different user and talk to Xero using that user. You can aslo implement this in an admin interface if you need to do this on behalf of the customer.

If you wish to clear the token without making any change in code, one way is to go to the files on the server and delete the token.json file directly and reload the app to clear token loaded in memory. I don't know how you can clear user login without calling the method ClearLoginSession() though.

Hope this is helpful.

Cheers
Alice
