### ISSUE TITLE
Access Token across network

### ISSUE THREAD

**Issue by Rajani-Bp** [AIKEJI-AU/Xero.OAuth2.Docs#8]
Hi Alice

How does the access token function in a business with multiple users on different computers? Can the token file be used on multiple computers within the same network ?

We would rather not have interactive login appear for other Users in the network until the token expires. How can this be accomplished?

BTW We already store Xero settings (Redirect url, Client ID, etc.) in our database; could we also store token (token.json) in our database and use them on other computers? I tried it, but the login screen appears! How do we bypass this?

Any advise? Thanks .

**Comment by alice-aikeji** [comment]
Hi Rajani,

User login is part of Xero's OAuth2 standard implementation. The aim is to have a person (Xero user) authorise the connection and communication. To do what you requested violates Xero's OAuth2 design because the user who authorised that particular machine and connection did not authorise the communication between Xero and other machines. For other machines to be authorised and communicate with Xero, a person (Xero user) needs to authorise it.

This is Xero's OAuth2 implementation that we cannot change. However, the new premium feature Xero launched may be of interest to you. However I'm personally unsure whether it will solve your problem because it is a machine-to-machine connection. If the token is still associated with a particular machine then you'd still need different token for each machine. The following feature is not supported by our library.
https://developer.xero.com/documentation/guides/oauth2/custom-connections#steps-for-building-a-custom-connection-on-behalf-of-a-client
https://developer.xero.com/documentation/guides/how-to-guides/machine-2-machine/#connecting-your-app-to-a-xero-account

Hope this information helps. Have a great weekend.
